In [1]:
import numpy as np

In [2]:
rg = np.random.default_rng(23)

# Transformation matrix (T)

In [3]:
T = rg.integers(-100, 100, size=(2, 3))
T

array([[-93,  38, -16],
       [ 28, -48, -75]])

# Original image (A)

In [4]:
ncols = 5
A = rg.integers(-5, 5, size=(2, ncols))
A = np.vstack([A, np.ones((1, ncols), dtype=np.int)])
A

array([[ 1, -4, -4,  1,  1],
       [ 3, -1, -3, -3, -3],
       [ 1,  1,  1,  1,  1]])

# Transformed image (B)

In [5]:
B = T @ A
B

array([[   5,  318,  242, -223, -223],
       [-191, -139,  -43,   97,   97]])

# Find transformation matrix (T')

$$
    TA = B
$$

$$
    \Leftrightarrow TAA^T = BA^T
$$

$$
    \Leftrightarrow TAA^T(AA^T)^{-1} = BA^T(AA^T)^{-1}
$$

$$
    \Leftrightarrow T = BA^T(AA^T)^{-1}
$$

In [6]:
B @ A.T @ np.linalg.inv(A @ A.T)


array([[-93.,  38., -16.],
       [ 28., -48., -75.]])